Separate test jobs
devcontainers/feature-starter pull request #27
Opened 2023-01-05 01:53 UTC by eitsupi

Separate the scenario tests from the auto-generated tests, since it is sufficient to run the scenario test once.

2023-01-05 18:51 UTC, samruddhikhandale requested changes
Thanks for the PR. Left few comments.

2023-01-05 18:51 UTC, samruddhikhandale commented on .github/workflows/test.yaml
> -        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .
> Separate the scenario tests from the auto-generated tests, since it is sufficient to run the scenario test once.

Good thought. This repo does not contain scenario tests for individual features. It only contains auto-generated tests (tested with `test` job) & `global-scenarios` (tested with `test-global` job). I believe that's the reason we didn't realize that the individual scenarios were running multiple times.

2023-01-05 18:51 UTC, samruddhikhandale commented on .github/workflows/test.yaml
> +  test-scenarios:
Would you be willing to add sample individual scenarios? Else, this job won't make sense for people who simply use this Template & don't add them by theirselves.

2023-01-05 18:51 UTC, samruddhikhandale commented on .github/workflows/test.yaml
> +          - julia
```suggestion
      matrix:
        features: [
          "color",
          "hello"
        ]
```

2023-01-06 10:36 UTC, eitsupi commented on .github/workflows/test.yaml
> +          - julia
Sorry, I noticed this issue in https://github.com/JuliaLang/devcontainer-features and copied it.......

2023-01-06 10:43 UTC, eitsupi commented on .github/workflows/test.yaml
> +  test-scenarios:
Done!

2023-01-06 17:48 UTC, samruddhikhandale reviewed
This looks amazing! Thank you! 👏 

![image](https://user-images.githubusercontent.com/24955913/211069297-4f864c62-ec08-4eb7-9c84-f9101281972a.png)


Left minor suggestions for the image property.

2023-01-06 17:48 UTC, samruddhikhandale commented on test/color/scenarios.json
> +        "image": "debian:stable-slim",
```suggestion
        "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
```

2023-01-06 17:48 UTC, samruddhikhandale commented on test/color/scenarios.json
> +        "image": "debian:stable-slim",
```suggestion
        "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
```

2023-01-06 17:48 UTC, samruddhikhandale commented on test/hello/scenarios.json
> +        "image": "debian:stable-slim",
```suggestion
        "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
```

2023-01-09 23:08 UTC, eitsupi commented
Thanks for your review. I think this is ready for merge.

2023-01-09 23:30 UTC, samruddhikhandale approved these changes
⚡

2023-01-09 23:31 UTC, merged